version: '3'

services:
  todoappwebapi:
    image: todoappwebapi
    build:
      context: .
      dockerfile: ToDo-App/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50100:80" # the aspnetcore container sets 80 as the default port
    depends_on:
      - db
      
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "QWEasd123%"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"