version: '3'

services:
  reactapp:
    image: reactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      
  todowebapi:
    image: todowebapi
    build:
      context: .
      dockerfile: ToDo-App/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50100:80" # the aspnetcore container sets 80 as the default port
    depends_on:
      - db
      
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "QWEasd123%"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"